"""empty message

Revision ID: f5c2c21e5c2c
Revises: dadb39d4a728
Create Date: 2021-08-25 17:11:07.565038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5c2c21e5c2c'
down_revision = 'dadb39d4a728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('profile_pic', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'profile_pic')
    # ### end Alembic commands ###
